### ISSUE TITLE
md_news_clickcount not work for me.

### ISSUE THREAD

**Issue by jooler** [cdaecke/md_news_clickcount#1]
I have install ext use composer and include setting of template was set;

and insert "<f:cObject typoscriptObjectPath="lib.newsIncreaseCount"/>" in detail template file,

but nothing in front
in backend insert new recoder in news,I have found views tab and count number.

**Comment by cdaecke** [comment]
`<f:cObject typoscriptObjectPath="lib.newsIncreaseCount"/>` just increases the counter for a news record, there is no output in the frontend. If you want to see the counted clicks in the frontend, use `{newsItem.mdNewsClickcountCount}`.

Does that answer your question?
