### ISSUE TITLE
Suggestion: Use middleware/ajax to count

### ISSUE THREAD

**Issue by georgringer** [cdaecke/md_news_clickcount#2]
I would propose to use a eid/ajax/middleware to update the stats.

+ maybe add the IP as well to avoid some spamming... 

if you are interested, I got some code around, contact me on slack

**Comment by cdaecke** [comment]
Hey Georg,

I appreciate any hint to make the extension better!

Find my message on slack.

Thanks a lot
chris

**Comment by cdaecke** [comment]
@georgringer I have just added the spam protection. Thanks a lot for your input!

I did not change the mechanism for updating the stats, so it is still done by adding `<f:cObject typoscriptObjectPath="lib.newsIncreaseCount"/>` to the detail template of a news record. I could not see any benefit for changing it. Did I oversee something?

**Comment by georgringer** [comment]
performance i guess

**Comment by cdaecke** [comment]
@georgringer Thanks again for your feedback!

Would you like to have a look at the attached commit? This commit changes the counting logic from the controller to a middleware. The tracking pixel can be included in the detail view of the news record by using the ViewHelper `GetCountImgViewHelper`, which makes sure, that the image is loaded in the correct path. This makes it possible, that a website is hosted in a subdirectory in staging environment and in the root directory in live context.

**Comment by cdaecke** [comment]
I have released a new version of the extension.

Once again: Thanks a lot for your input!
