### ISSUE TITLE
CleanupLogCommand::execute and ClearViewsCommand::execute not compatible with Command::execute

### ISSUE THREAD

**Issue by cbammann** [cdaecke/md_news_clickcount#4]
Hi,

after upgrading our project to typo3 12, we got an error from your extension:

`Fatal error: Declaration of Mediadreams\MdNewsClickcount\Command\CleanupLogCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/mediadreams/md_news_clickcount/Classes/Command/CleanupLogCommand.php on line 47`

The same error also appears in the `execute` function in the class `ClearViewsCommand`. It seems that these functions are not compatible with the function in the base class from Symfony. When I change the code manually and add the return type `: int` to each of these functions, the error disappears. Can you please fix this?

Thanks!

**Comment by cdaecke** [comment]
Thanks for pointing that out.

A new release (v3.0.2) of the extension is available.
