### ISSUE TITLE
Compatibility with News v12

### ISSUE THREAD

**Issue by simonschaufi** [cdaecke/md_news_clickcount#5]
News 12.0 is not allowed in composer.json. Please make it compatible. Thank you very much for this great extension!

**Comment by cdaecke** [comment]
Did you test and can you confirm, that the extension works with `ext:news` v12?

**Comment by simonschaufi** [comment]
No, I didn't test it myself. I was hoping that you would to it because you hopefully already have a testing environment.

**Comment by cdaecke** [comment]
Version 3.0.3 of the extension is released, which is compatible with `ext:news` v12.

**Comment by simonschaufi** [comment]
Thank you very much!
