### ISSUE TITLE
Click counter always increases even if I set `daysForNextCount` > 0

### ISSUE THREAD

**Issue by simonschaufi** [cdaecke/md_news_clickcount#6]
Hi, I would expect the click counter to only increase once a day when I set `daysForNextCount` = 1 in settings but that is not the case. Whenevery I reload the news item, the click counter increases.

I guess there is a bug in the middleware.

**Comment by cdaecke** [comment]
Please add the following code in line 103 of the `CountMiddleware`:

    \TYPO3\CMS\Core\Utility\DebugUtility::debug($this->configuration['daysForNextCount']);
    exit;

https://github.com/cdaecke/md_news_clickcount/blob/edf3268aa59a5f471c3d9c497e996c18dc016713/Classes/Middleware/CountMiddleware.php#L103-L107

Call `https://yourtest.ddev.site/md-newsimg-2.gif`. Do you get the `1` for the debug output?

**Comment by simonschaufi** [comment]
Yes, this is the output: `'1' (1 chars)`

And this is the SQL that is executed:

```sql
SELECT COUNT(*) 
FROM `tx_mdnewsclickcount_log` 
WHERE (`news` = :dcValue1) AND (`ip` = :dcValue2) AND (`log_date` >= :dcValue3)
```

with the following parameters:

```
Array
(
    [0] => 2
    [1] => 127.0.0.1
    [2] => 2024-11-11
)
```

but even though I have several log entries already in the table, the result is still `0`. So there is a bug in the SQL query.

When I execute the SQL directly in mysql:

```sql
SELECT COUNT(*)
FROM `tx_mdnewsclickcount_log`
WHERE (`news` = 2) AND (`ip` = '127.0.0.1') AND (`log_date` >= '2024-11-11');
```
I get 4 as result.

I found the bug!

There is a cast to int which is wrong!

This line must be like this:

```php
$queryBuilder->expr()->gte('log_date', $queryBuilder->createNamedParameter($this->getAllowedTimeFrame(), \PDO::PARAM_STR)),
```

then it works correctly because date is a string and not an int!

PS: and `news` parameter should be an int instead ;)

**Comment by cdaecke** [comment]
Thanks for debugging!

Could you please double check, if the attached fix is working?

**Comment by simonschaufi** [comment]
there is no extra int cast needed as there is already a cast in place. the rest works fine

**Comment by cdaecke** [comment]
Thanks four your feedback, which is incorporated now.

News version of the extension (v.3.0.4) is published.
